---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddis-db
  namespace: redis-namespace
  labels:
    app: reddis-db
spec:
  selector:
    matchLabels:
      app: reddis-db
  replicas: 1
  template:
    metadata:
      labels:
        app: reddis-db
    spec:
      containers:
        - name: reddis-db
          image: redis:latest
          imagePullPolicy: Never
          ports:
          - protocol: TCP
            containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-visit-counter
  namespace: redis-namespace
  labels:
    app: web-visit-counter
spec:
  selector:
    matchLabels:
      app: web-visit-counter
  replicas: 1
  template:
    metadata:
      labels:
        app: web-visit-counter
    spec:
      containers:
        - name: web-visit-counter
          image: gradlecanvacr.azurecr.io/redis-web-counter:144ed38
          imagePullPolicy: Never
          ports:
          - protocol: TCP
            containerPort: 8080


