apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-namespace
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis-namespace
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: "Always"
        ports:
        - protocol: TCP
          containerPort: 6379