---
apiVersion: v1
kind: Service
metadata:
  name: counter-svc
  namespace: redis-namespace
spec:
  type: LoadBalancer
  selector:
    app: web-visit-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reddis-db-svc
  namespace: redis-namespaces
spec:
  type: LoadBalancer
  selector:
    app: reddis-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379