---
apiVersion: v1
kind: Service
metadata:
  name: counter-svc
  namespace: redis-namespace
spec:
  type: LoadBalancer
  selector:
    app: web-visit-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-visit-counter
  namespace: redis-namespace
  labels:
    app: web-visit-counter
spec:
  selector:
    matchLabels:
      app: web-visit-counter
  replicas: 1
  template:
    metadata:
      labels:
        app: web-visit-counter
    spec:
      containers:
        - name: web-visit-counter
          image: gradlecanvacr.azurecr.io/redis-web-counter:28e2677
          imagePullPolicy: Never
          ports:
            - protocol: TCP
              containerPort: 8080

